/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Activity {
    #[serde(rename = "actorName", skip_serializing_if = "Option::is_none")]
    pub actor_name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "actorProfileUrl", skip_serializing_if = "Option::is_none")]
    pub actor_profile_url: Option<String>,
    #[serde(rename = "dateTimeUtc", skip_serializing_if = "Option::is_none")]
    pub date_time_utc: Option<String>,
}

impl Activity {
    pub fn new() -> Activity {
        Activity {
            actor_name: None,
            description: None,
            actor_profile_url: None,
            date_time_utc: None,
        }
    }
}


