/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */

/// ConsentDocumentIssuer : ConsentDocumentIssuer : Consent document issuer details.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConsentDocumentIssuer {
    /// Document issuer id.
    #[serde(rename = "id")]
    pub id: String,
    /// Document issuer name.
    #[serde(rename = "name")]
    pub name: String,
}

impl ConsentDocumentIssuer {
    /// ConsentDocumentIssuer : Consent document issuer details.
    pub fn new(id: String, name: String) -> ConsentDocumentIssuer {
        ConsentDocumentIssuer {
            id,
            name,
        }
    }
}


