/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */

/// CreateConsentRequest : CreateConsentRequest : Create consent request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateConsentRequest {
    /// Consent request template id
    #[serde(rename = "consentTemplateId")]
    pub consent_template_id: String,
    #[serde(rename = "receiver")]
    pub receiver: Box<crate::models::ConsentRequestReceiver>,
}

impl CreateConsentRequest {
    /// CreateConsentRequest : Create consent request.
    pub fn new(consent_template_id: String, receiver: crate::models::ConsentRequestReceiver) -> CreateConsentRequest {
        CreateConsentRequest {
            consent_template_id,
            receiver: Box::new(receiver),
        }
    }
}


