/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreditCardHolder {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "creditCardId")]
    pub credit_card_id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "dob")]
    pub dob: String,
    #[serde(rename = "mobile")]
    pub mobile: String,
    #[serde(rename = "nominee")]
    pub nominee: crate::models::HoldingNominee,
    #[serde(rename = "landline", skip_serializing_if = "Option::is_none")]
    pub landline: Option<String>,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "pan")]
    pub pan: String,
    #[serde(rename = "ckycCompliance")]
    pub ckyc_compliance: bool,
}

impl CreditCardHolder {
    pub fn new(id: uuid::Uuid, credit_card_id: uuid::Uuid, name: String, dob: String, mobile: String, nominee: crate::models::HoldingNominee, address: String, email: String, pan: String, ckyc_compliance: bool) -> CreditCardHolder {
        CreditCardHolder {
            id,
            credit_card_id,
            name,
            dob,
            mobile,
            nominee,
            landline: None,
            address,
            email,
            pan,
            ckyc_compliance,
        }
    }
}


