/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */

/// DataProcessingAgreement : DataProcessingAgreement : Data processing agreement details.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataProcessingAgreement {
    /// Agreement id.
    #[serde(rename = "id")]
    pub id: String,
    /// Agreement name.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "issuerType")]
    pub issuer_type: crate::models::IssuerType,
    /// Agreement attachment file URL.
    #[serde(rename = "agreementUrl")]
    pub agreement_url: String,
}

impl DataProcessingAgreement {
    /// DataProcessingAgreement : Data processing agreement details.
    pub fn new(id: String, name: String, issuer_type: crate::models::IssuerType, agreement_url: String) -> DataProcessingAgreement {
        DataProcessingAgreement {
            id,
            name,
            issuer_type,
            agreement_url,
        }
    }
}


