/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */

/// DataProviderDetails : DataProviderDetails: Data provider details.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataProviderDetails {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "category")]
    pub category: String,
    #[serde(rename = "logoUrl", skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<String>,
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    #[serde(rename = "supportEmail", skip_serializing_if = "Option::is_none")]
    pub support_email: Option<String>,
    #[serde(rename = "helpLineNumber", skip_serializing_if = "Option::is_none")]
    pub help_line_number: Option<String>,
    #[serde(rename = "privacyPolicy", skip_serializing_if = "Option::is_none")]
    pub privacy_policy: Option<String>,
    #[serde(rename = "termOfService", skip_serializing_if = "Option::is_none")]
    pub term_of_service: Option<String>,
    #[serde(rename = "dataProtectionOfficer")]
    pub data_protection_officer: Box<crate::models::DataProtectionOfficer>,
    #[serde(rename = "supportedDocumentTypes")]
    pub supported_document_types: Vec<crate::models::SupportedDocumentType>,
    #[serde(rename = "supportedAccountTypes")]
    pub supported_account_types: Vec<String>,
}

impl DataProviderDetails {
    /// DataProviderDetails: Data provider details.
    pub fn new(id: String, name: String, category: String, data_protection_officer: crate::models::DataProtectionOfficer, supported_document_types: Vec<crate::models::SupportedDocumentType>, supported_account_types: Vec<String>) -> DataProviderDetails {
        DataProviderDetails {
            id,
            name,
            category,
            logo_url: None,
            website: None,
            support_email: None,
            help_line_number: None,
            privacy_policy: None,
            term_of_service: None,
            data_protection_officer: Box::new(data_protection_officer),
            supported_document_types,
            supported_account_types,
        }
    }
}


