/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataConsentRequestedDocument {
    #[serde(rename = "custom_key", skip_serializing_if = "Option::is_none")]
    pub custom_key: Option<String>,
    #[serde(rename = "drn", skip_serializing_if = "Option::is_none")]
    pub drn: Option<String>,
    #[serde(rename = "documentTypeId", skip_serializing_if = "Option::is_none")]
    pub document_type_id: Option<String>,
    #[serde(rename = "documentIdentifier", skip_serializing_if = "Option::is_none")]
    pub document_identifier: Option<String>,
}

impl DataConsentRequestedDocument {
    pub fn new() -> DataConsentRequestedDocument {
        DataConsentRequestedDocument {
            custom_key: None,
            drn: None,
            document_type_id: None,
            document_identifier: None,
        }
    }
}


