/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataConsentDetailsDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::DataConsentStatus>,
    #[serde(rename = "approvedAtUtc", skip_serializing_if = "Option::is_none")]
    pub approved_at_utc: Option<String>,
    #[serde(rename = "rejectedAtUtc", skip_serializing_if = "Option::is_none")]
    pub rejected_at_utc: Option<String>,
    #[serde(rename = "expiresAtUtc", skip_serializing_if = "Option::is_none")]
    pub expires_at_utc: Option<String>,
    #[serde(rename = "requestedAtUtc", skip_serializing_if = "Option::is_none")]
    pub requested_at_utc: Option<String>,
    #[serde(rename = "requester", skip_serializing_if = "Option::is_none")]
    pub requester: Option<Box<crate::models::DataConsentRequesterDto>>,
    #[serde(rename = "consentDetails", skip_serializing_if = "Option::is_none")]
    pub consent_details: Option<Box<crate::models::GetConsentTemplateDetailsDto>>,
    #[serde(rename = "identifiers", skip_serializing_if = "Option::is_none")]
    pub identifiers: Option<Vec<crate::models::DataConsentIdentifier>>,
    #[serde(rename = "approvedDocuments", skip_serializing_if = "Option::is_none")]
    pub approved_documents: Option<Vec<crate::models::DataConsentRequestedDocument>>,
    #[serde(rename = "approvedFinancials", skip_serializing_if = "Option::is_none")]
    pub approved_financials: Option<Vec<crate::models::DataConsentRequestedFinancialAccount>>,
}

impl DataConsentDetailsDto {
    pub fn new() -> DataConsentDetailsDto {
        DataConsentDetailsDto {
            id: None,
            status: None,
            approved_at_utc: None,
            rejected_at_utc: None,
            expires_at_utc: None,
            requested_at_utc: None,
            requester: None,
            consent_details: None,
            identifiers: None,
            approved_documents: None,
            approved_financials: None,
        }
    }
}


