/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataConsentDocumentDetailsDto {
    #[serde(rename = "fieldTitle")]
    pub field_title: String,
    #[serde(rename = "fieldSlug")]
    pub field_slug: String,
    #[serde(rename = "supportedDocumentTypeCategoryDetails")]
    pub supported_document_type_category_details: Vec<crate::models::SupportedDocumentTypeCategoryDetailsDto>,
    #[serde(rename = "requirement")]
    pub requirement: crate::models::DocumentsRequired,
}

impl DataConsentDocumentDetailsDto {
    pub fn new(field_title: String, field_slug: String, supported_document_type_category_details: Vec<crate::models::SupportedDocumentTypeCategoryDetailsDto>, requirement: crate::models::DocumentsRequired) -> DataConsentDocumentDetailsDto {
        DataConsentDocumentDetailsDto {
            field_title,
            field_slug,
            supported_document_type_category_details,
            requirement,
        }
    }
}


