/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DigitalSignature {
    #[serde(rename = "signedBy", skip_serializing_if = "Option::is_none")]
    pub signed_by: Option<String>,
    #[serde(rename = "certIssuedBy", skip_serializing_if = "Option::is_none")]
    pub cert_issued_by: Option<String>,
    #[serde(rename = "validFrom", skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<String>,
    #[serde(rename = "validTill", skip_serializing_if = "Option::is_none")]
    pub valid_till: Option<String>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(rename = "sha1Digest", skip_serializing_if = "Option::is_none")]
    pub sha1_digest: Option<String>,
}

impl DigitalSignature {
    pub fn new() -> DigitalSignature {
        DigitalSignature {
            signed_by: None,
            cert_issued_by: None,
            valid_from: None,
            valid_till: None,
            reason: None,
            location: None,
            sha1_digest: None,
        }
    }
}


