/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EquityHolding {
    #[serde(rename = "issuerName")]
    pub issuer_name: String,
    #[serde(rename = "exchange")]
    pub exchange: String,
    #[serde(rename = "isin")]
    pub isin: String,
    #[serde(rename = "units")]
    pub units: i64,
    #[serde(rename = "investmentDateTime", skip_serializing_if = "Option::is_none")]
    pub investment_date_time: Option<String>,
    #[serde(rename = "rate", skip_serializing_if = "Option::is_none")]
    pub rate: Option<String>,
    #[serde(rename = "lastTradedPrice", skip_serializing_if = "Option::is_none")]
    pub last_traded_price: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl EquityHolding {
    pub fn new(issuer_name: String, exchange: String, isin: String, units: i64) -> EquityHolding {
        EquityHolding {
            issuer_name,
            exchange,
            isin,
            units,
            investment_date_time: None,
            rate: None,
            last_traded_price: None,
            description: None,
        }
    }
}


