/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FinancialAccountCreditCardTransaction {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "txn_type")]
    pub txn_type: crate::models::CreditCardTransactionType,
    #[serde(rename = "txn_date")]
    pub txn_date: String,
    #[serde(rename = "amount")]
    pub amount: f32,
    #[serde(rename = "value_date")]
    pub value_date: String,
    #[serde(rename = "narration")]
    pub narration: String,
    #[serde(rename = "statement_date")]
    pub statement_date: String,
    #[serde(rename = "mcc")]
    pub mcc: String,
    #[serde(rename = "masked_card_number")]
    pub masked_card_number: String,
}

impl FinancialAccountCreditCardTransaction {
    pub fn new(r#type: String, id: String, txn_type: crate::models::CreditCardTransactionType, txn_date: String, amount: f32, value_date: String, narration: String, statement_date: String, mcc: String, masked_card_number: String) -> FinancialAccountCreditCardTransaction {
        FinancialAccountCreditCardTransaction {
            r#type,
            id,
            txn_type,
            txn_date,
            amount,
            value_date,
            narration,
            statement_date,
            mcc,
            masked_card_number,
        }
    }
}


