/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "r#type")]
pub enum FinancialAccount {
    #[serde(rename="Aif")]
    FinancialAccountAif {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="BillPayment")]
    FinancialAccountBillPayment {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="Bond")]
    FinancialAccountBond {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="CIS")]
    FinancialAccountCis {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="CertificateOfDeposit")]
    FinancialAccountCertificateOfDeposit {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="CommercialPaper")]
    FinancialAccountCommercialPaper {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="CreditCard")]
    FinancialAccountCreditCard {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "balance")]
        balance: f64,
        #[serde(rename = "profile")]
        profile: Box<crate::models::CreditCardProfile>,
        #[serde(rename = "summary")]
        summary: Box<crate::models::CreditCardSummary>,
        #[serde(rename = "masked_account_number")]
        masked_account_number: String,
        #[serde(rename = "linked_account_ref")]
        linked_account_ref: String,
        #[serde(rename = "version")]
        version: f32,
    },
    #[serde(rename="Debenture")]
    FinancialAccountDebenture {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="Deposit")]
    FinancialAccountDeposit {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="Epf")]
    FinancialAccountEpf {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="Equity")]
    FinancialAccountEquity {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "balance")]
        balance: f64,
        #[serde(rename = "profile")]
        profile: Box<crate::models::Profile>,
        #[serde(rename = "summary")]
        summary: Box<crate::models::EquitySummary>,
        #[serde(rename = "masked_account_number")]
        masked_account_number: String,
        #[serde(rename = "linked_account_ref")]
        linked_account_ref: String,
        #[serde(rename = "version")]
        version: f32,
    },
    #[serde(rename="Etf")]
    FinancialAccountEtf {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="GovtSecurity")]
    FinancialAccountGovtSecurity {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="Idr")]
    FinancialAccountIdr {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="InsurancePolicy")]
    FinancialAccountInsurancePolicy {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="Invit")]
    FinancialAccountInvit {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="Loan")]
    FinancialAccountLoan {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="MutualFund")]
    FinancialAccountMutualFund {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "balance")]
        balance: f64,
        #[serde(rename = "profile")]
        profile: Box<crate::models::Profile>,
        #[serde(rename = "summary")]
        summary: Box<crate::models::MutualFundSummary>,
        #[serde(rename = "masked_account_number")]
        masked_account_number: String,
        #[serde(rename = "linked_account_ref")]
        linked_account_ref: String,
        #[serde(rename = "version")]
        version: f32,
    },
    #[serde(rename="Nps")]
    FinancialAccountNps {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="Ppf")]
    FinancialAccountPpf {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="RecurringDeposit")]
    FinancialAccountRecurringDeposit {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="Reit")]
    FinancialAccountReit {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="Sip")]
    FinancialAccountSip {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="TermDeposit")]
    FinancialAccountTermDeposit {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
    #[serde(rename="Ulip")]
    FinancialAccountUlip {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "identifier")]
        identifier: String,
        #[serde(rename = "amount")]
        amount: f64,
    },
}




