/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FinancialAccountSip {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "investment_value")]
    pub investment_value: f64,
    #[serde(rename = "current_value")]
    pub current_value: f64,
    #[serde(rename = "currency_code")]
    pub currency_code: String,
    #[serde(rename = "plan_info")]
    pub plan_info: Box<crate::models::SipPlanInformation>,
    #[serde(rename = "investment_info")]
    pub investment_info: Box<crate::models::SipInvestmentInformation>,
    #[serde(rename = "holder")]
    pub holder: Box<crate::models::Holder>,
    #[serde(rename = "transactions")]
    pub transactions: bool,
}

impl FinancialAccountSip {
    pub fn new(r#type: String, id: String, name: String, investment_value: f64, current_value: f64, currency_code: String, plan_info: crate::models::SipPlanInformation, investment_info: crate::models::SipInvestmentInformation, holder: crate::models::Holder, transactions: bool) -> FinancialAccountSip {
        FinancialAccountSip {
            r#type,
            id,
            name,
            investment_value,
            current_value,
            currency_code,
            plan_info: Box::new(plan_info),
            investment_info: Box::new(investment_info),
            holder: Box::new(holder),
            transactions,
        }
    }
}


