/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FinancialAccountTransactionEquityTransaction {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "currency_code")]
    pub currency_code: String,
    #[serde(rename = "txn_type")]
    pub txn_type: crate::models::EquityTransactionsType,
    #[serde(rename = "units")]
    pub units: String,
    #[serde(rename = "transacted_at_utc")]
    pub transacted_at_utc: String,
}

impl FinancialAccountTransactionEquityTransaction {
    pub fn new(r#type: String, id: String, amount: String, currency_code: String, txn_type: crate::models::EquityTransactionsType, units: String, transacted_at_utc: String) -> FinancialAccountTransactionEquityTransaction {
        FinancialAccountTransactionEquityTransaction {
            r#type,
            id,
            amount,
            currency_code,
            txn_type,
            units,
            transacted_at_utc,
        }
    }
}


