/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FinancialAccounts {
    #[serde(rename = "drn", skip_serializing_if = "Option::is_none")]
    pub drn: Option<String>,
    #[serde(rename = "required_details", skip_serializing_if = "Option::is_none")]
    pub required_details: Option<Vec<crate::models::FinancialAccountDetailsRequired>>,
    #[serde(rename = "start_date", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(rename = "end_date", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
}

impl FinancialAccounts {
    pub fn new() -> FinancialAccounts {
        FinancialAccounts {
            drn: None,
            required_details: None,
            start_date: None,
            end_date: None,
        }
    }
}


