/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "r#type")]
pub enum FinancialAccountTransaction {
    #[serde(rename="AifTransaction")]
    FinancialAccountAifTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="BillPaymentTransaction")]
    FinancialAccountBillPaymentTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="BondTransaction")]
    FinancialAccountBondTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="CISTransaction")]
    FinancialAccountCisTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="CertificateOfDepositTransaction")]
    FinancialAccountCertificateOfDepositTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="CommercialPaperTransaction")]
    FinancialAccountCommercialPaperTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="CreditCardTransaction")]
    FinancialAccountCreditCardTransaction {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "txn_type")]
        txn_type: crate::models::CreditCardTransactionType,
        #[serde(rename = "txn_date")]
        txn_date: String,
        #[serde(rename = "amount")]
        amount: f32,
        #[serde(rename = "value_date")]
        value_date: String,
        #[serde(rename = "narration")]
        narration: String,
        #[serde(rename = "statement_date")]
        statement_date: String,
        #[serde(rename = "mcc")]
        mcc: String,
        #[serde(rename = "masked_card_number")]
        masked_card_number: String,
    },
    #[serde(rename="DebentureTransaction")]
    FinancialAccountDebentureTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="DepositTransaction")]
    FinancialAccountDepositTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="EpfTransaction")]
    FinancialAccountEpfTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="EquityTransaction")]
    FinancialAccountEquityTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="EtfTransaction")]
    FinancialAccountEtfTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="GovtSecurityTransaction")]
    FinancialAccountGovtSecurityTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="IdrTransaction")]
    FinancialAccountIdrTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="InsurancePolicyTransaction")]
    FinancialAccountInsurancePolicyTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="InvitTransaction")]
    FinancialAccountInvitTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="LoanTransaction")]
    FinancialAccountLoanTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="MutualFundTransaction")]
    FinancialAccountMutualFundTransaction {
        #[serde(rename = "id")]
        id: String,
        #[serde(rename = "amc")]
        amc: String,
        #[serde(rename = "registrar")]
        registrar: String,
        #[serde(rename = "scheme_code")]
        scheme_code: String,
        #[serde(rename = "scheme_plan")]
        scheme_plan: crate::models::MutualFundSchemePlan,
        #[serde(rename = "isin")]
        isin: String,
        #[serde(rename = "amfi_code")]
        amfi_code: String,
        #[serde(rename = "fund_type")]
        fund_type: crate::models::MutualFundFundType,
        #[serde(rename = "scheme_option")]
        scheme_option: crate::models::MutualFundSchemeOption,
        #[serde(rename = "scheme_types")]
        scheme_types: crate::models::MutualFundSchemeType,
        #[serde(rename = "scheme_category")]
        scheme_category: crate::models::MutualFundSchemeCategory,
        #[serde(rename = "ucc")]
        ucc: String,
        #[serde(rename = "amount")]
        amount: String,
        #[serde(rename = "closing_units")]
        closing_units: String,
        #[serde(rename = "lien_units")]
        lien_units: String,
        #[serde(rename = "nav")]
        nav: String,
        #[serde(rename = "nav_date")]
        nav_date: String,
        #[serde(rename = "order_date")]
        order_date: String,
        #[serde(rename = "execution_date")]
        execution_date: String,
        #[serde(rename = "lockin_flag")]
        lockin_flag: String,
        #[serde(rename = "lockin_days")]
        lockin_days: String,
        #[serde(rename = "mode")]
        mode: crate::models::MutualFundHoldingMode,
        #[serde(rename = "narration")]
        narration: String,
    },
    #[serde(rename="NpsTransaction")]
    FinancialAccountNpsTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="PpfTransaction")]
    FinancialAccountPpfTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="RecurringDepositTransaction")]
    FinancialAccountRecurringDepositTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="ReitTransaction")]
    FinancialAccountReitTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="SipTransaction")]
    FinancialAccountSipTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="TermDepositTransaction")]
    FinancialAccountTermDepositTransaction {
        #[serde(rename = "id")]
        id: String,
    },
    #[serde(rename="UlipTransaction")]
    FinancialAccountUlipTransaction {
        #[serde(rename = "id")]
        id: String,
    },
}




