/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */

/// IdentityField : IdentityField : Identity field of Consent request template.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityField {
    /// Field title.
    #[serde(rename = "title")]
    pub title: String,
    /// Field description.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Field key.
    #[serde(rename = "key")]
    pub key: String,
    /// Field data type.
    #[serde(rename = "dataType")]
    pub data_type: String,
}

impl IdentityField {
    /// IdentityField : Identity field of Consent request template.
    pub fn new(title: String, key: String, data_type: String) -> IdentityField {
        IdentityField {
            title,
            description: None,
            key,
            data_type,
        }
    }
}


