/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IndividualConsentRequestTemplateDetailsDataLife {
    /// Life unit. Example: days, hours, minutes.
    #[serde(rename = "unit")]
    pub unit: String,
    /// Life value in number.
    #[serde(rename = "value")]
    pub value: String,
}

impl IndividualConsentRequestTemplateDetailsDataLife {
    pub fn new(unit: String, value: String) -> IndividualConsentRequestTemplateDetailsDataLife {
        IndividualConsentRequestTemplateDetailsDataLife {
            unit,
            value,
        }
    }
}


