/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */

/// IndividualDataConsentRequestResponse : Individual Data Consent Request Response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IndividualDataConsentRequestResponse {
    /// Consent request id
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Consent request template id
    #[serde(rename = "templateId", skip_serializing_if = "Option::is_none")]
    pub template_id: Option<String>,
    /// Requested date time in utc zone
    #[serde(rename = "requestedAtUtc", skip_serializing_if = "Option::is_none")]
    pub requested_at_utc: Option<String>,
    /// Request expires date time in utc zone
    #[serde(rename = "requestExpiresAtUtc", skip_serializing_if = "Option::is_none")]
    pub request_expires_at_utc: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::DataConsentStatus>,
    /// Requested transaction id
    #[serde(rename = "transactionId", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
}

impl IndividualDataConsentRequestResponse {
    /// Individual Data Consent Request Response.
    pub fn new() -> IndividualDataConsentRequestResponse {
        IndividualDataConsentRequestResponse {
            id: None,
            template_id: None,
            requested_at_utc: None,
            request_expires_at_utc: None,
            status: None,
            transaction_id: None,
        }
    }
}


