/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaginatedListOfDataProcessingAgreements {
    #[serde(rename = "pageNo")]
    pub page_no: i32,
    #[serde(rename = "pageSize")]
    pub page_size: i32,
    #[serde(rename = "totalPage")]
    pub total_page: i32,
    #[serde(rename = "items")]
    pub items: Vec<crate::models::DataProcessingAgreement>,
}

impl PaginatedListOfDataProcessingAgreements {
    pub fn new(page_no: i32, page_size: i32, total_page: i32, items: Vec<crate::models::DataProcessingAgreement>) -> PaginatedListOfDataProcessingAgreements {
        PaginatedListOfDataProcessingAgreements {
            page_no,
            page_size,
            total_page,
            items,
        }
    }
}


