/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */

/// Receiver : Consent request receiver details



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Receiver {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<crate::models::ReceiverType>,
    /// Consent request receiver identifiers
    #[serde(rename = "identifiers", skip_serializing_if = "Option::is_none")]
    pub identifiers: Option<Vec<crate::models::StringStringKeyValuePair>>,
    #[serde(rename = "identificationStrategy", skip_serializing_if = "Option::is_none")]
    pub identification_strategy: Option<crate::models::IdentificationStrategy>,
}

impl Receiver {
    /// Consent request receiver details
    pub fn new() -> Receiver {
        Receiver {
            _type: None,
            identifiers: None,
            identification_strategy: None,
        }
    }
}


