/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */

/// SelectedFinancialAccountType : SelectedFinancialAccountType : Selected financial account type of financial account field of consent request template.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SelectedFinancialAccountType {
    #[serde(rename = "subCategory")]
    pub sub_category: Box<crate::models::FinancialAccountSubCategoryType>,
    /// DRNs.
    #[serde(rename = "drns")]
    pub drns: Vec<String>,
}

impl SelectedFinancialAccountType {
    /// SelectedFinancialAccountType : Selected financial account type of financial account field of consent request template.
    pub fn new(sub_category: crate::models::FinancialAccountSubCategoryType, drns: Vec<String>) -> SelectedFinancialAccountType {
        SelectedFinancialAccountType {
            sub_category: Box::new(sub_category),
            drns,
        }
    }
}


