/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SipPlanInformation {
    #[serde(rename = "amc", skip_serializing_if = "Option::is_none")]
    pub amc: Option<String>,
    #[serde(rename = "registrar", skip_serializing_if = "Option::is_none")]
    pub registrar: Option<String>,
    #[serde(rename = "scheme")]
    pub scheme: String,
    #[serde(rename = "isin")]
    pub isin: String,
    #[serde(rename = "folio_number", skip_serializing_if = "Option::is_none")]
    pub folio_number: Option<String>,
    #[serde(rename = "nav", skip_serializing_if = "Option::is_none")]
    pub nav: Option<String>,
    #[serde(rename = "dividend_type")]
    pub dividend_type: String,
    #[serde(rename = "creation_date", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<String>,
}

impl SipPlanInformation {
    pub fn new(scheme: String, isin: String, dividend_type: String) -> SipPlanInformation {
        SipPlanInformation {
            amc: None,
            registrar: None,
            scheme,
            isin,
            folio_number: None,
            nav: None,
            dividend_type,
            creation_date: None,
        }
    }
}


