/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SupportedDocumentDetailsDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "typeId")]
    pub type_id: String,
    #[serde(rename = "logoUrl")]
    pub logo_url: String,
    #[serde(rename = "storageUrl")]
    pub storage_url: String,
    #[serde(rename = "issuedBy")]
    pub issued_by: String,
    #[serde(rename = "uploadedAtUtc")]
    pub uploaded_at_utc: String,
}

impl SupportedDocumentDetailsDto {
    pub fn new(id: String, type_id: String, logo_url: String, storage_url: String, issued_by: String, uploaded_at_utc: String) -> SupportedDocumentDetailsDto {
        SupportedDocumentDetailsDto {
            id,
            type_id,
            logo_url,
            storage_url,
            issued_by,
            uploaded_at_utc,
        }
    }
}


