/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TermDeposit {
    #[serde(rename = "account_number")]
    pub account_number: String,
    #[serde(rename = "account_type")]
    pub account_type: crate::models::TermDepositAccountType,
    #[serde(rename = "issuer_name")]
    pub issuer_name: String,
    #[serde(rename = "issuer_logo_url")]
    pub issuer_logo_url: String,
    #[serde(rename = "current_value")]
    pub current_value: f64,
    #[serde(rename = "currency_code")]
    pub currency_code: String,
    #[serde(rename = "account_details")]
    pub account_details: Box<crate::models::TermDepositAccountDetails>,
}

impl TermDeposit {
    pub fn new(account_number: String, account_type: crate::models::TermDepositAccountType, issuer_name: String, issuer_logo_url: String, current_value: f64, currency_code: String, account_details: crate::models::TermDepositAccountDetails) -> TermDeposit {
        TermDeposit {
            account_number,
            account_type,
            issuer_name,
            issuer_logo_url,
            current_value,
            currency_code,
            account_details: Box::new(account_details),
        }
    }
}


