/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UriDetails {
    #[serde(rename = "aadhaar")]
    pub aadhaar: String,
    #[serde(rename = "uri")]
    pub uri: String,
    #[serde(rename = "docType")]
    pub doc_type: String,
    #[serde(rename = "docName")]
    pub doc_name: String,
    #[serde(rename = "docId")]
    pub doc_id: String,
    #[serde(rename = "issuedOn")]
    pub issued_on: String,
    #[serde(rename = "validFrom")]
    pub valid_from: String,
    #[serde(rename = "validTo", skip_serializing_if = "Option::is_none")]
    pub valid_to: Option<String>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
}

impl UriDetails {
    pub fn new(aadhaar: String, uri: String, doc_type: String, doc_name: String, doc_id: String, issued_on: String, valid_from: String) -> UriDetails {
        UriDetails {
            aadhaar,
            uri,
            doc_type,
            doc_name,
            doc_id,
            issued_on,
            valid_from,
            valid_to: None,
            timestamp: None,
            action: None,
        }
    }
}


