/*
 * My Data My Consent - Developer API
 *
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserDataConsentInfoDto {
    #[serde(rename = "consentRequestId", skip_serializing_if = "Option::is_none")]
    pub consent_request_id: Option<String>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "consentTemplateId", skip_serializing_if = "Option::is_none")]
    pub consent_template_id: Option<String>,
    #[serde(rename = "consentPurpose", skip_serializing_if = "Option::is_none")]
    pub consent_purpose: Option<String>,
    #[serde(rename = "consentDescription", skip_serializing_if = "Option::is_none")]
    pub consent_description: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::DataConsentStatus>,
    #[serde(rename = "createdAtUtc", skip_serializing_if = "Option::is_none")]
    pub created_at_utc: Option<String>,
    #[serde(rename = "consentSentToUser", skip_serializing_if = "Option::is_none")]
    pub consent_sent_to_user: Option<String>,
}

impl UserDataConsentInfoDto {
    pub fn new() -> UserDataConsentInfoDto {
        UserDataConsentInfoDto {
            consent_request_id: None,
            user_id: None,
            consent_template_id: None,
            consent_purpose: None,
            consent_description: None,
            status: None,
            created_at_utc: None,
            consent_sent_to_user: None,
        }
    }
}


